# Generated by Django 5.2.7 on 2025-11-05 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="socialaccount",
            old_name="added_at",
            new_name="created_at",
        ),
    ]
