# Generated by Django 5.2.7 on 2025-11-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_rename_added_at_socialaccount_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialaccount",
            name="platform",
            field=models.CharField(
                choices=[
                    ("instagram", "Instagram"),
                    ("linkedin", "LinkedIn"),
                    ("twitter", "Twitter"),
                    ("facebook", "Facebook"),
                ],
                max_length=20,
            ),
        ),
    ]
